"""Add CreatedAt to Note model

Revision ID: 428f318c07c3
Revises: 5000d41cdbc0
Create Date: 2025-05-13 02:09:50.327580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '428f318c07c3'
down_revision = '5000d41cdbc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('CreatedAt', sa.DateTime(), nullable=True))

    with op.batch_alter_table('Notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('TaskId', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('IsRead', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(None, 'Tasks', ['TaskId'], ['TaskId'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('IsRead')
        batch_op.drop_column('TaskId')

    with op.batch_alter_table('Notes', schema=None) as batch_op:
        batch_op.drop_column('CreatedAt')

    # ### end Alembic commands ###
