"""Add CreatedAt field to Question model

Revision ID: 5000d41cdbc0
Revises: a8cb4cccd3d6
Create Date: 2025-05-12 23:46:17.392934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5000d41cdbc0'
down_revision = 'a8cb4cccd3d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('CreatedAt', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Questions', schema=None) as batch_op:
        batch_op.drop_column('CreatedAt')

    # ### end Alembic commands ###
