"""Question modeline CreatedAt ve UpdatedAt alanları eklendi

Revision ID: a8cb4cccd3d6
Revises: 
Create Date: 2025-05-12 23:41:48.055117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8cb4cccd3d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Questions', schema=None) as batch_op:
        batch_op.drop_column('Explanation')
        batch_op.drop_column('ImagePath')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ImagePath', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('Explanation', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
